version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    container_name: MariaDB
    restart: unless-stopped
    networks:
      - main
    environment:
      MARIADB_DATABASE: app
      MARIADB_USER: test
      MARIADB_PASSWORD: 123
      MARIADB_ROOT_PASSWORD: override
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
  api:
    image: python:3.10-buster
    container_name: API
    restart: unless-stopped
    working_dir: /app
    command:
      - ./run.sh
    networks:
      - main
    ports:
      - "2356:2356"
    volumes:
      - ".:/app"
      - "./files:/files"
networks:
  main:
    driver: bridge