version: "3.9"
networks:
  main:
    driver: bridge
services:
  cassandra:
    image: bitnami/cassandra
    container_name: cassandra
    restart: unless-stopped
    networks:
      - main
    ports:
      - "9042:9042"
    volumes:
      - "./db/cassandra:/bitnami/cassandra/data"
    environment:
      CASSANDRA_PASSWORD_SEEDER: "yes"
      CASSANDRA_USER: "api"
      CASSANDRA_PASSWORD: "Nhth3td.ZY_@wHw9agws"
  redis:
    image: bitnami/redis
    container_name: redis
    restart: unless-stopped
    networks:
      - main
    ports:
      - "6379:6379"
    volumes:
      - './db/redis:/bitnami/redis/data'
    environment:
      REDIS_PASSWORD: "z-crBrrXvDm@!or@fA33"
