version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    restart: unless-stopped
    command: --authentication_policy=mysql_native_password
    networks:
      - main
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: test
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: override
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
  api:
    image: python:3.10-buster
    container_name: API
    restart: unless-stopped
    working_dir: /app
    command:
      - ./run.sh
    networks:
      - main
    ports:
      - "2356:2356"
    volumes:
      - ".:/app"
      - "./files:/files"
networks:
  main:
    driver: bridge